#!/bin/bash
# rails-app-creator

# This script creates new rails applications with a variety of common 
#   configurations that can be passed in as command-line flags.



# Prints help information
usage()
{
cat << EOF
Here are usage instructions
--name Appname
-h -v --haml --rspec --cucumber --jasmine
EOF
}



# Adds Haml gems to Gemfile
addHamlGems()
{
if [[ $VERBOSE -eq 1 ]]; then echo "Adding Haml gems to Gemfile."; fi
cat << EOF >> ./$APPNAME/Gemfile
  
# Use Haml for templating
gem 'haml'
gem 'haml-rails'
EOF
}



# Replaces ERB layout with Haml layout
replaceErbLayout()
{
# Remove ERB layout file
if [[ $VERBOSE -eq 1 ]]; then echo "Deleting ERB layout file."; fi
rm ./$APPNAME/app/views/layouts/application.html.erb

# Create Haml layout file
if [[ $VERBOSE -eq 1 ]]; then echo "Creating Haml layout file."; fi
cat << EOF >> ./$APPNAME/app/views/layouts/application.html.haml
!!! 5

%html
  %head
    %title $APPNAME
      = stylesheet_link_tag 'application', media: "all", "data-turbolinks-track" => true
      = javascript_include_tag 'application', "data-turbolinks-track" => true
      = csrf_meta_tags

  %body
    =yield
EOF
}



# Add gems for rspec, cucumber, and jasmine to test/development group
addTestingGemsDevTestGroup()
{
if [[ $VERBOSE -eq 1 ]]
then echo "Adding testing gems to :development, :test group."
fi

# Begin Development/Test Group
cat << EOF >> ./$APPNAME/Gemfile

# Testing Gems
group :development, :test do
EOF

# RSpec Development/Test Group
if [[ $RSPEC -eq 1 ]]
then
cat << EOF >> ./$APPNAME/Gemfile
  gem 'rspec-rails'
  gem 'factory_girl_rails'
  gem 'faker'
EOF
fi

# Jasmine Development/Test Group
if [[ $JASMINE -eq 1 ]] 
then
cat << EOF >> ./$APPNAME/Gemfile
  gem 'jasmine-rails'
  gem 'jasmine-jquery-rails'
  gem 'guard-jasmine'
EOF
fi

# End Development/Test Group
echo "end" >> ./$APPNAME/Gemfile
}



# Add gems for rspec, cucumber, and jasmine to test group
addTestingGemsTestGroup()
{
if [[ $VERBOSE -eq 1 ]]
then echo "Adding testing gems to :test group."
fi

# Begin Test Group
cat << EOF >> ./$APPNAME/Gemfile

# Testing Gems
group :test do
EOF

# RSpec Test Group
if [[ $RSPEC -eq 1 ]]
then
cat << EOF >> ./$APPNAME/Gemfile
  gem 'shoulda-matchers'
  gem 'guard-rspec', :require => false
  gem 'simplecov', :require => false
EOF
fi

# Cucumber Test Group
if [[ $CUCUMBER -eq 1 ]] 
then
cat << EOF >> ./$APPNAME/Gemfile
  gem 'cucumber-rails', require: false
  gem 'selenium-webdriver'
  gem 'database_cleaner'
  gem 'launchy'
  gem 'guard-cucumber'
EOF
fi

# End Test Group
echo "end" >> ./$APPNAME/Gemfile
}



# Set up RSpec in application
rspecSetup()
{
if [[ $VERBOSE -eq 1 ]]; then echo "Installing RSpec into application."; fi
./$APPNAME/rails g rspec:install

if [[ $VERBOSE -eq 1 ]]; then echo "Fixing .rspec file."; fi
cat << EOF > ./$APPNAME/.rspec
--color -fd
--require rails_helper
EOF

if [[ $VERBOSE -eq 1 ]]; then echo "Creating binstub for RSpec."; fi
./$APPNAME/bundle binstubs rspec-core
}



# Set up Cucumber in application
cucumberSetup()
{
}



# Set up jasmine in application
jasmineSetup()
{
}



# Set up SimpleCov
simplecovSetup()
{
}



# Variables
APPNAME=""
VERBOSE=0
HAML=0
RSPEC=0
CUCUMBER=0
JASMINE=0



# Parse command parameters
while :
do
  case $1 in
    -h | --help)
      usage
      exit 0
      ;;
    -v | --verbose)
      VERBOSE=1
      shift
      ;;
    --name)
      APPNAME=$2
      shift 2
      ;;
    --haml)
      HAML=1
      shift
      ;;
    --rspec)
      RSPEC=1
      shift
      ;;
    --cucumber)
      CUCUMBER=1
      shift
      ;;
    --jasmine)
      JASMINE=1
      shift
      ;;
    -* | --*)
      echo "Unknown option encountered: $1"
      usage
      exit -1
      ;;
    *)
      break
      ;;
  esac
done



# Check that an application name was provided
if [[ -z $APPNAME ]]
then
  echo "A name for the new application must be provided."
  usage
  exit -1
fi



# Create new rails application
CREATECOMMAND="rails new $APPNAME"
if [[ $RSPEC -eq 1 ]]
then
  # If using RSpec, omit Test::Unit directory
  CREATECOMMAND="$CREATECOMMAND -T"
fi
if [[ $VERBOSE -eq 1 ]]; then echo "Creating new rails application."; fi
$CREATECOMMAND



# Add HAML support, if HAML option is set
if [[ $HAML -eq 1 ]]
then
  addHamlGems
  replaceErbLayout
fi



# Add Gems for RSpec, Cucumber, and Jasmine if options are set
if [[ $RSPEC -eq 1 || $JASMINE -eq 1 ]]
then
  addTestingGemsDevTestGroup
fi
if [[ $RSPEC -eq 1 || $CUCUMBER -eq 1 ]]
then
  addTestingGemsTestGroup
fi
bundle



# Add RSpec setup
if [[ $RSPEC -eq 1 ]]
then
  rspecSetup
fi



# Add Cucumber setup
if [[ $CUCUMBER -eq 1 ]]
then
  cucumberSetup
fi



# Add jasmine setup
if [[ $JASMINE -eq 1 ]]
then
  jasmineSetup
fi



# Add simplecov setup
if [[ $RSPEC -eq 1 || $CUCUMBER -eq 1 ]]
then
  simplecovSetup
fi


# Exit
exit 0
