#!/bin/bash
# rails-app-creator

# This script creates new rails applications with a variety of common 
#   configurations that can be passed in as command-line flags.


# Prints help information
usage()
{
cat << EOF
Here are usage instructions
--name Appname
-h -v --haml --rspec --cucumber --jasmine
EOF
}


# Adds Haml gems to Gemfile
addHamlGems()
{
if [[ $VERBOSE -eq 1 ]]; then echo "Adding Haml gems to Gemfile."; fi
cat << EOF >> ./$APPNAME/Gemfile
  
# Use Haml for templating
gem 'haml'
gem 'haml-rails'
EOF
}


# Replaces ERB layout with Haml layout
replaceErbLayout()
{
# Remove ERB layout file
if [[ $VERBOSE -eq 1 ]]; then echo "Deleting ERB layout file."; fi
rm ./$APPNAME/app/views/layouts/application.html.erb

# Create Haml layout file
if [[ $VERBOSE -eq 1 ]]; then echo "Creating Haml layout file."; fi
cat <<- EOF >> ./$APPNAME/app/views/layouts/application.html.haml
!!! 5

%html
  %head
    %title $APPNAME
      = stylesheet_link_tag 'application', media: "all", "data-turbolinks-track" => true
      = javascript_include_tag 'application', "data-turbolinks-track" => true
      = csrf_meta_tags

  %body
    =yield
EOF
}


# Variables
APPNAME=""
VERBOSE=0
HAML=0
RSPEC=0
CUCUMBER=0
JASMINE=0


# Parse command parameters
while :
do
  case $1 in
    -h | --help)
      usage
      exit 0
      ;;
    -v | --verbose)
      VERBOSE=1
      shift
      ;;
    --name)
      APPNAME=$2
      shift 2
      ;;
    --haml)
      HAML=1
      shift
      ;;
    --rspec)
      RSPEC=1
      shift
      ;;
    --cucumber)
      CUCUMBER=1
      shift
      ;;
    --jasmine)
      JASMINE=1
      shift
      ;;
    -* | --*)
      echo "Unknown option encountered: $1"
      usage
      exit -1
      ;;
    *)
      break
      ;;
  esac
done


# Check that an application name was provided
if [[ -z $APPNAME ]]
then
  echo "A name for the new application must be provided."
  usage
  exit -1
fi


# Create new rails application
CREATECOMMAND="rails new $APPNAME"
if [[ $RSPEC -eq 1 ]]
then
  # If using RSpec, omit Test::Unit directory
  CREATECOMMAND="$CREATECOMMAND -T"
fi
if [[ $VERBOSE -eq 1 ]]; then echo "Creating new rails application."; fi
$CREATECOMMAND


# Add HAML support, if HAML option is set
if [[ $HAML -eq 1 ]]
then
  addHamlGems
  replaceErbLayout
fi


# Exit
exit 0
